services:
  # Backend API Service
  - type: web
    name: jobtradesasa-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: jobtradesasa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/categories
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: jobtradesasa-db
    databaseName: jobtradesasa
    plan: starter
    region: oregon
    postgresMajorVersion: 15
